name: DLT_STALE
on:
  workflow_dispatch:

jobs: 
  dltStaleBranches:
    runs-on: ubuntu-latest
    steps:
      - name: Delete stale branches
        run:  |
          echo -------./ListBranchScript.sh ---------------------
          bash .github/ListBranchScript.sh
