name: DLT_STALE
on:
  workflow_dispatch:

jobs: 
  dltStaleBranches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} 
          
      - name: Delete stale branches
        run:  |
          echo -----git branch-------
          git branch -a
          for k in $(git branch | sed /\*/d); do 
            if [ -z "$(git log -1 --before='1 week ago' -s $k)" ]; then
              git branch -D $k
            fi
          done
          
          
