name: DLT_STALE
on:
  workflow_dispatch:

jobs: 
  dltStaleBranches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Delete stale branches
        run:  |
          echo -----git ls-remote --heads git://github.com/git/git.git-------
          git ls-remote --heads git://github.com/git/git.git
          for k in $(git branch | sed /\*/d); do 
            if [ -z "$(git log -1 --before='1 week ago' -s $k)" ]; then
              git branch -D $k
            fi
          done
          
          
