name: DLT_STALE
on:
  workflow_dispatch:

jobs: 
  dltStaleBranches:
    runs-on: ubuntu-latest
    steps:
      
      - name: List stale branches
        run:  |
            git clone https://github.com/2115-27/angular-realworld-example-app.git
            cd angular-realworld-example-app/
            echo ----git branch -av----
            git branch -av
            echo ---git log --since='1 week ago'----------
            git log --since='1 week ago'
        env:
           GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
          
          
